src/v6/apps/urls.py
from django.conf.urls import include, url

from django.contrib.auth import views as auth_views
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'apps.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^login/$', auth_views.login, name='login'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^app/jogo/', include('jogo.urls', namespace='jogo')),
    url(r'^app/jogo/(?P<jogoId>\d+)/jogada/', include('jogada.urls', namespace='jogada')),
    url(r'^app/jogada/', include('jogada.urls', namespace='jogada')),    
    url(r'^$', 'apps.views.start'),
    url(r'^app/$', 'apps.views.home'),
    url(r'^app/sair$', 'apps.views.sair'),
]

src/v6/jogo/urls.py
from django.conf.urls import patterns, url

from jogo import views
from jogada import views as views_jogada

urlpatterns = patterns('',
  url(r'^$', views.jogo_list, name='jogo_list'),
  url(r'^new$', views.jogo_create, name='jogo_new'),
  url(r'^edit/(?P<pk>\d+)$', views.jogo_update, name='jogo_edit'),
  url(r'^delete/(?P<pk>\d+)$', views.jogo_delete, name='jogo_delete'),  
  #url(r'../jogada$', views.jogo_jogadas, name='jogo_jogadas'),
  url(r'^(?P<pk>\d+)/jogada$', views.jogo_jogadas, name='jogo_jogadas'),
)

src/v6/jogo/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.contrib.auth.forms import User


class Jogo(models.Model):
	jogador1 = models.ForeignKey(User, related_name="jogador1")
	jogador2 = models.ForeignKey(User, related_name='jogador2')
	finalizado = models.BooleanField(default=False)
	iniciado = models.DateTimeField(default=timezone.now)
	jogadasMaxima = models.IntegerField(default=0)
	jogadasJogador1 = models.IntegerField(default=0)
	jogadasJogador2 = models.IntegerField(default=0)
	vencedor = models.ForeignKey(User, related_name="vencedor", null=True)

	def __str__(self):
		return "Jogo jogador1: " + self.jogador1.username + " vs jogador2:" + self.jogador2.username + ". Qtd Jogadas: " + str(self.jogadasMaxima) + ". Qtde Jog 1: " + str(self.jogadasJogador1) + ". Qtde Jog 2: " + str(self.jogadasJogador2) + ", vencedor: " + str(self.vencedor)

class Tabuleiro(models.Model):
    jogo = models.ForeignKey(Jogo, related_name="jogo")
    tamanho = models.IntegerField(default=0)

    def __str__(self):
        return "Tabuleiro do Jogo " + str(self.jogo)

class Posicao(models.Model):
    linha = models.IntegerField(default=0)
    coluna = models.IntegerField(default=0)
    barco = models.BooleanField(default=False)
    verificado = models.BooleanField(default=False)
    acerto = models.BooleanField(default=False)    
    tabuleiro = models.ForeignKey(Tabuleiro, related_name='tabuleiro', default=0)

    def __str__(self):
        return "Posicao [" + str(self.linha) + "][" + str(self.coluna) + "] barco=" + str(self.barco)

src/v6/jogo/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm

from jogo.models import Jogo
from jogada.models import Jogada

from utils.batalha import BatalhaNaval

class JogoForm(ModelForm):
    class Meta:
        model = Jogo
        fields = ['jogador1', 'jogador2', 'jogadasMaxima']

@login_required
def jogo_list(request, template_name='jogo/jogo_list.html'):
    jogo = Jogo.objects.all()
    data = {}
    data['object_list'] = jogo
    return render(request, template_name, data)

@login_required
def jogo_jogadas(request, pk, template_name='jogada/jogada_list.html'):    
    return redirect('jogada:jogada_list', pk)

@login_required
def jogo_create(request, template_name='jogo/jogo_form.html'):
    form = JogoForm(request.POST or None)
    if form.is_valid():
        jogo = form.save()        
        # registra tabuleiro com configurações
        BatalhaNaval().tabuleiroGerar(jogo)        

        return redirect('jogo:jogo_list')
    return render(request, template_name, {'form':form})

@login_required
def jogo_update(request, pk, template_name='jogo/jogo_form.html'):
    jogo= get_object_or_404(Jogo, pk=pk)
    form = JogoForm(request.POST or None, instance=jogo)
    if form.is_valid():
        form.save()
        return redirect('jogo:jogo_list')
    return render(request, template_name, {'form':form})

def jogo_delete(request, pk, template_name='jogo/jogo_confirm_delete.html'):
    jogo= get_object_or_404(Jogo, pk=pk)    
    if request.method=='POST':
        jogo.delete()
        return redirect('jogo:jogo_list')
    return render(request, template_name, {'object':jogo})

src/v6/jogo/templates/jogo/jogo_confirm_delete.html
<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>

src/v6/jogo/templates/jogo/jogo_form.html
{% extends 'base.html' %}

{% block content %}

<h1>Jogo</h1>

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

{% endblock %}

src/v6/jogo/templates/jogo/jogo_list.html
{% extends 'base.html' %}

{% block content %}


<h1>Jogos</h1>

    <a href="{% url 'jogo:jogo_new' %}">New</a> <br><br>
    <table>
        <tr>
            <th>Jogadores</th>
            <th>Finalizado</th>
            <th>Vencedor</th>
            <th></th>                    
        </tr>
        {% for jogo in object_list %}
        <tr>
            <td>{{ jogo.jogador1.username }} vs {{ jogo.jogador2.username }}</td>
            <td>{{ jogo.finalizado }}</td>
            <td>{{ jogo.vencedor }}</td>
            <td>
                <a href="{% url 'jogo:jogo_edit' jogo.id %}">edit</a>
                <a href="{% url 'jogo:jogo_delete' jogo.id %}">delete</a>
                <a href="{% url 'jogo:jogo_jogadas' jogo.id %}">jogadas</a>
            </td>
        </tr>
        {% endfor %}

    </table>

{% endblock %}