src/v6/apps/urls.py
from django.conf.urls import include, url

from django.contrib.auth import views as auth_views
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'apps.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^login/$', auth_views.login, name='login'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^app/jogo/', include('jogo.urls', namespace='jogo')),
    url(r'^app/jogo/(?P<jogoId>\d+)/jogada/', include('jogada.urls', namespace='jogada')),
    url(r'^app/jogada/', include('jogada.urls', namespace='jogada')),    
    url(r'^$', 'apps.views.start'),
    url(r'^app/$', 'apps.views.home'),
    url(r'^app/sair$', 'apps.views.sair'),
]

src/v6/jogada/urls.py
from django.conf.urls import patterns, url

from jogada import views

urlpatterns = patterns('',  
  url(r'^new$', views.jogada_create, name='jogada_new'),
  url(r'^edit/(?P<pk>\d+)$', views.jogada_update, name='jogada_edit'),
  url(r'^delete/(?P<pk>\d+)$', views.jogada_delete, name='jogada_delete'),  
  url(r'^$', views.jogada_list, name='jogada_list')  
)

src/v6/jogada/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.forms import User 
from django.utils import timezone
from jogo.models import Jogo 

class Jogada(models.Model):
	jogo = models.ForeignKey(Jogo, related_name="jogada_jogo")
	autor = models.ForeignKey(User, related_name="jogada_autor")	
	linha = models.CharField(max_length=2)
	coluna = models.CharField(max_length=2)	
	registro = models.DateTimeField(default=timezone.now)	
	acerto = models.BooleanField(default=False)

	def __str__(self):
		return "Jogada de " + self.autor.username + " realizada no dia " + self.registro.strftime('%d %B %Y') + " : linha " + self.linha + ", coluna " + self.coluna + ", acerto: " + str(self.acerto) 

src/v6/jogada/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.forms import ModelForm
from django.core import validators
from django.contrib import messages 

from jogo.models import Jogo
from jogada.models import Jogada
from utils.batalha import BatalhaNaval

class JogadaForm(ModelForm):
    class Meta:
        model = Jogada
        fields = ['linha', 'coluna']

@login_required
def jogada_list(request, jogoId, template_name='jogada/jogada_list.html'):
    jogada = Jogada.objects.filter(jogo_id=jogoId)
    data = {}
    data['object_list'] = jogada
    data['jogoId'] = int(jogoId)    

    jogo = Jogo.objects.get(id=jogoId)
    data['jogo'] = jogo

    return render(request, template_name, data)

@login_required
def jogada_create(request, jogoId, template_name='jogada/jogada_form.html'):    
    jogoAtual = Jogo.objects.get(pk=jogoId)     # obtém jogo da url
    form = JogadaForm(request.POST or None)

    if form.is_valid():
        form.registro = timezone.now()
        jogada = form.save(commit=False)
        jogada.jogo = jogoAtual                 # define jogo da url
        jogada.autor = request.user             # define autor usuário logado        
        resultado = BatalhaNaval().permiteJogada(jogada)
        if resultado == "":
            jogada.save()
            BatalhaNaval().atualizar(jogada)            

            return redirect('jogada:jogada_list', jogoId)
        else:
            messages.error(request, resultado)

    return render(request, template_name, {'form':form, 'jogoAtual': jogoAtual, 'autor': request.user.username})

@login_required
def jogada_update(request, pk, jogoId, template_name='jogada/jogada_form.html'):
    jogada= get_object_or_404(Jogada, pk=pk)
    form = JogadaForm(request.POST or None, instance=jogada)
    if form.is_valid():
        form.save()
        return redirect('jogada:jogada_list', jogoId)
    return render(request, template_name, {'form':form})

@login_required
def jogada_delete(request, pk, template_name='jogada/jogada_confirm_delete.html'):
    jogada= get_object_or_404(Jogada, pk=pk)    
    if request.method=='POST':
        jogada.delete()
        return redirect('jogada:jogada_list')
    return render(request, template_name, {'object':jogada})

src/v6/jogada/templates/jogada/jogada_confirm_delete.html
{% extends 'base.html' %} 

{% block content %}

<form method="post">{% csrf_token %}
    <div>
        Tem certeza que deseja excuir "{{ object }}" ?
        <input type="submit" value="Submit" />
    </div>    
</form>

{% endblock %}

src/v6/jogada/templates/jogada/jogada_form.html
{% extends 'base.html' %}

{% block content %}


    {% if messages %}
        {% for message in messages %}
        <div style="color: red">
            <span>{{message}}</span>
        </div>            
        {% endfor %}
    {% endif %}



    <h3>Nova Jogada</h3>    

    <a href="{% url 'jogada:jogada_list' jogoAtual.id %}">back</a> <br><br>

    <form method="post">{% csrf_token %}        
        <label>Jogo:</label>
        <span>{{jogoAtual}}</span><br>
        
        <label>Autor:</label>
        <span>{{autor}}</span><br>     

        {{ form.as_p }}
        <input type="submit" value="Submit" />    
    </form>            

{% endblock %}

src/v6/jogada/templates/jogada/jogada_list.html
{% extends 'base.html' %} 

{% block content %} 

    {% if messages %} 
        {% for message in messages %}
        <div class="alert alert-danger">
            <span>{{message}}</span>
        </div>
        {% endfor %} 
    {% endif %}


    <h3>Jogadas</h3>

    {%  if jogo.vencedor %}

        O vencedor é <b>{{jogo.vencedor.username}}</b>!!! <br/><br/>

    {%  endif %}

        
    <a href="{% url 'jogada:jogada_new' jogoId %}">new</a>    
    
    <table>
        <tr>
            <th>Jogo</th>
            <th>Autor</th>
            <th>Linha</th>
            <th>Coluna</th>
            <th>Acerto</th>
            <th></th>
        </tr>
        {% for jogada in object_list %}
        <tr>
            <td> {{ jogada.jogo.pk }} </td>
            <td> {{ jogada.autor.username }} </td>
            <td> {{ jogada.linha }} </td>
            <td> {{ jogada.coluna }} </td>
            <td> {{ jogada.acerto }} </td>
            <td>                
                
            </td>
        </tr>
        {% endfor %}
    </table>   
{% endblock %}